---
- hosts:
    - rancherServer
  become: True
  gather_facts: True
  vars_files:
    - vars/default.yml
    - vars/private.yml
  roles:
    - { role: rancher, tags: rancher }
    # - { role: haproxy, tags: haproxy, when: "groups['loadbalancer']|count == 0"}
  tags:
    - rancher

- hosts:
    - node
  become: True
  gather_facts: True
  vars_files:
    - vars/default.yml
    - vars/private.yml
  roles:
    - { role: rancher, tags: rancher }
  tags:
    - rancher
