---
- name: create docker setup dirs.
  file: 
    path: "{{ item }}"
    state: directory
    #owner: root 
    #group: root
    mode: 0755
  with_items:
    - '/opt/bin'
  become: true

- name: Template daemon.json
  template:
    src: daemon.json.j2
    dest: '{{ dockerConfDir }}/daemon.json'
#    owner: root
#    mode: 0644
    force: yes
  become: true
  notify: 
    - restart docker

- name: Template http-proxy.conf
  template:
    src: http-proxy.conf
    dest: '{{dockerSystemdDir}}/http-proxy.conf'
    owner: root
    mode: 0644
    force: yes
  become: true
  notify: 
    - restart docker

- name: Template https-proxy.conf
  template:
    src: https-proxy.conf
    dest: '{{dockerSystemdDir}}/https-proxy.conf'
    owner: root
    mode: 0644
    force: yes
  become: true
  notify: 
    - restart docker
    
- name: Template docker.service.j2
  template:
    src: docker.service.j2
    dest: '/etc/systemd/system/multi-user.target.wants/docker.service'
    owner: root
    mode: 0644
    force: yes
  become: true
  notify: 
    - restart docker