---
- name: Install rancher-cli
  shell: "curl -kL {{rancher_cli_download_url}} | tar zx --strip-components 2 -C ${HOME}/bin"
  args:
    creates: ${HOME}/bin/rancher
  # become: yes

- name: Set permissions rancher
  file: path=${HOME}/bin/rancher mode=0755
  # become: yes
